#!/bin/bash

npm run clean
npm run fmt
npm run build
for page in feed contacts interests followers settings actor; do
  mkdir -p dist/$page
  pushd dist/$page
  ln -s ../index.html index.html
  popd
done
pushd dist && \
  tar -cf - . | \
  ssh $dhs 'cd ~/conversely.social/ && tar -xf -' && \
  popd

